
<?php

use Illuminate\Database\Seeder;
use App\Models\Industry;

class IndustryTableSeeder extends Seeder {

    public function run()
    {
        Industry::create(['id' => '47', 'name' => 'Accounting']);
        Industry::create(['id' => '94', 'name' => 'Airlines/Aviation']);
        Industry::create(['id' => '120', 'name' => 'Alternative Dispute Resolution']);
        Industry::create(['id' => '125', 'name' => 'Alternative Medicine']);
        Industry::create(['id' => '127', 'name' => 'Animation']);
        Industry::create(['id' => '19', 'name' => 'Apparel & Fashion']);
        Industry::create(['id' => '50', 'name' => 'Architecture & Planning']);
        Industry::create(['id' => '111','name' => 'Arts and Crafts']);
        Industry::create(['id' => '53', 'name' => 'Automotive']);
        Industry::create(['id' => '52', 'name' => 'Aviation & Aerospace']);
        Industry::create(['id' => '41', 'name' => 'Banking']);
        Industry::create(['id' => '12', 'name' => 'Biotechnology']);
        Industry::create(['id' => '36', 'name' => 'Broadcast Media']);
        Industry::create(['id' => '49', 'name' => 'Building Materials']);
        Industry::create(['id' => '138', 'name' => 'Business Supplies and Equipment']);
        Industry::create(['id' => '129', 'name' => 'Capital Markets']);
        Industry::create(['id' => '54', 'name' => 'Chemicals']);
        Industry::create(['id' => '90', 'name' => 'Civic & Social Organization']);
        Industry::create(['id' => '51', 'name' => 'Civil Engineering']);
        Industry::create(['id' => '128', 'name' => 'Commercial Real Estate']);
        Industry::create(['id' => '118', 'name' => 'Computer & Network Security']);
        Industry::create(['id' => '109', 'name' => 'Computer Games']);
        Industry::create(['id' => '3', 'name' => 'Computer Hardware']);
        Industry::create(['id' => '5', 'name' => 'Computer Networking']);
        Industry::create(['id' => '4', 'name' => 'Computer Software']);
        Industry::create(['id' => '48', 'name' => 'Construction']);
        Industry::create(['id' => '24', 'name' => 'Consumer Electronics']);
        Industry::create(['id' => '25', 'name' => 'Consumer Goods']);
        Industry::create(['id' => '91', 'name' => 'Consumer Services']);
        Industry::create(['id' => '18', 'name' => 'Cosmetics']);
        Industry::create(['id' => '65', 'name' => 'Dairy']);
        Industry::create(['id' => '1', 'name' => 'Defense & Space']);
        Industry::create(['id' => '99', 'name' => 'Design']);
        Industry::create(['id' => '69', 'name' => 'Education Management']);
        Industry::create(['id' => '132', 'name' => 'E-Learning']);
        Industry::create(['id' => '112', 'name' => 'Electrical/Electronic Manufacturing']);
        Industry::create(['id' => '28', 'name' => 'Entertainment']);
        Industry::create(['id' => '86', 'name' => 'Environmental Services']);
        Industry::create(['id' => '110', 'name' => 'Events Services']);
        Industry::create(['id' => '76', 'name' => 'Executive Office']);
        Industry::create(['id' => '122', 'name' => 'Facilities Services']);
        Industry::create(['id' => '63', 'name' => 'Farming']);
        Industry::create(['id' => '43', 'name' => 'Financial Services']);
        Industry::create(['id' => '38', 'name' => 'Fine Art']);
        Industry::create(['id' => '66', 'name' => 'Fishery']);
        Industry::create(['id' => '34', 'name' => 'Food & Beverages']);
        Industry::create(['id' => '23', 'name' => 'Food Production']);
        Industry::create(['id' => '101', 'name' => 'Fund-Raising']);
        Industry::create(['id' => '26', 'name' => 'Furniture']);
        Industry::create(['id' => '29', 'name' => 'Gambling & Casinos']);
        Industry::create(['id' => '145', 'name' => 'Glass, Ceramics & Concrete']);
        Industry::create(['id' => '75', 'name' => 'Government Administration']);
        Industry::create(['id' => '148', 'name' => 'Government Relations']);
        Industry::create(['id' => '140', 'name' => 'Graphic Design']);
        Industry::create(['id' => '124', 'name' => 'Health, Wellness and Fitness']);
        Industry::create(['id' => '68', 'name' => 'Higher Education']);
        Industry::create(['id' => '14', 'name' => 'Hospital & Health Care']);
        Industry::create(['id' => '31', 'name' => 'Hospitality']);
        Industry::create(['id' => '137', 'name' => 'Human Resources']);
        Industry::create(['id' => '134', 'name' => 'Import and Export']);
        Industry::create(['id' => '88', 'name' => 'Individual & Family Services']);
        Industry::create(['id' => '147', 'name' => 'Industrial Automation']);
        Industry::create(['id' => '84', 'name' => 'Information Services']);
        Industry::create(['id' => '96', 'name' => 'Information Technology and Services']);
        Industry::create(['id' => '42', 'name' => 'Insurance']);
        Industry::create(['id' => '74', 'name' => 'International Affairs']);
        Industry::create(['id' => '141', 'name' => 'International Trade and Development']);
        Industry::create(['id' => '6', 'name' => 'Internet']);
        Industry::create(['id' => '45', 'name' => 'Investment Banking']);
        Industry::create(['id' => '46', 'name' => 'Investment Management']);
        Industry::create(['id' => '73', 'name' => 'Judiciary']);
        Industry::create(['id' => '77', 'name' => 'Law Enforcement']);
        Industry::create(['id' => '9', 'name' => 'Law Practice']);
        Industry::create(['id' => '10', 'name' => 'Legal Services']);
        Industry::create(['id' => '72', 'name' => 'Legislative Office']);
        Industry::create(['id' => '30', 'name' => 'Leisure, Travel & Tourism']);
        Industry::create(['id' => '85', 'name' => 'Libraries']);
        Industry::create(['id' => '116', 'name' => 'Logistics and Supply Chain']);
        Industry::create(['id' => '143', 'name' => 'Luxury Goods & Jewelry']);
        Industry::create(['id' => '55', 'name' => 'Machinery']);
        Industry::create(['id' => '11', 'name' => 'Management Consulting']);
        Industry::create(['id' => '95', 'name' => 'Maritime']);
        Industry::create(['id' => '97', 'name' => 'Market Research']);
        Industry::create(['id' => '80', 'name' => 'Marketing and Advertising']);
        Industry::create(['id' => '135', 'name' => 'Mechanical or Industrial Engineering']);
        Industry::create(['id' => '126', 'name' => 'Media Production']);
        Industry::create(['id' => '17', 'name' => 'Medical Devices']);
        Industry::create(['id' => '13', 'name' => 'Medical Practice']);
        Industry::create(['id' => '139', 'name' => 'Mental Health Care']);
        Industry::create(['id' => '71', 'name' => 'Military']);
        Industry::create(['id' => '56', 'name' => 'Mining & Metals']);
        Industry::create(['id' => '35', 'name' => 'Motion Pictures and Film']);
        Industry::create(['id' => '37', 'name' => 'Museums and Institutions']);
        Industry::create(['id' => '115', 'name' => 'Music']);
        Industry::create(['id' => '114', 'name' => 'Nanotechnology']);
        Industry::create(['id' => '81', 'name' => 'Newspapers']);
        Industry::create(['id' => '100', 'name' => 'Non-Profit Organization Management']);
        Industry::create(['id' => '57', 'name' => 'Oil & Energy']);
        Industry::create(['id' => '113', 'name' => 'Online Media']);
        Industry::create(['id' => '123', 'name' => 'Outsourcing/Offshoring']);
        Industry::create(['id' => '87', 'name' => 'Package/Freight Delivery']);
        Industry::create(['id' => '146', 'name' => 'Packaging and Containers']);
        Industry::create(['id' => '61', 'name' => 'Paper & Forest Products']);
        Industry::create(['id' => '39', 'name' => 'Performing Arts']);
        Industry::create(['id' => '15', 'name' => 'Pharmaceuticals']);
        Industry::create(['id' => '131', 'name' => 'Philanthropy']);
        Industry::create(['id' => '136', 'name' => 'Photography']);
        Industry::create(['id' => '117', 'name' => 'Plastics']);
        Industry::create(['id' => '107', 'name' => 'Political Organization']);
        Industry::create(['id' => '67', 'name' => 'Primary/Secondary Education']);
        Industry::create(['id' => '83', 'name' => 'Printing']);
        Industry::create(['id' => '105', 'name' => 'Professional Training & Coaching']);
        Industry::create(['id' => '102', 'name' => 'Program Development']);
        Industry::create(['id' => '79', 'name' => 'Public Policy']);
        Industry::create(['id' => '98', 'name' => 'Public Relations and Communications']);
        Industry::create(['id' => '78', 'name' => 'Public Safety']);
        Industry::create(['id' => '82', 'name' => 'Publishing']);
        Industry::create(['id' => '62', 'name' => 'Railroad Manufacture']);
        Industry::create(['id' => '64', 'name' => 'Ranching']);
        Industry::create(['id' => '44', 'name' => 'Real Estate']);
        Industry::create(['id' => '40', 'name' => 'Recreational Facilities and Services']);
        Industry::create(['id' => '89', 'name' => 'Religious Institutions']);
        Industry::create(['id' => '144', 'name' => 'Renewables & Environment']);
        Industry::create(['id' => '70', 'name' => 'Research']);
        Industry::create(['id' => '32', 'name' => 'Restaurants']);
        Industry::create(['id' => '27', 'name' => 'Retail']);
        Industry::create(['id' => '121', 'name' => 'Security and Investigations']);
        Industry::create(['id' => '7', 'name' => 'Semiconductors']);
        Industry::create(['id' => '58', 'name' => 'Shipbuilding']);
        Industry::create(['id' => '20', 'name' => 'Sporting Goods']);
        Industry::create(['id' => '33', 'name' => 'Sports']);
        Industry::create(['id' => '104', 'name' => 'Staffing and Recruiting']);
        Industry::create(['id' => '22', 'name' => 'Supermarkets']);
        Industry::create(['id' => '8', 'name' => 'Telecommunications']);
        Industry::create(['id' => '60', 'name' => 'Textiles']);
        Industry::create(['id' => '130', 'name' => 'Think Tanks']);
        Industry::create(['id' => '21', 'name' => 'Tobacco']);
        Industry::create(['id' => '108', 'name' => 'Translation and Localization']);
        Industry::create(['id' => '92', 'name' => 'Transportation/Trucking/Railroad']);
        Industry::create(['id' => '59', 'name' => 'Utilities']);
        Industry::create(['id' => '106', 'name' => 'Venture Capital & Private Equity']);
        Industry::create(['id' => '16', 'name' => 'Veterinary']);
        Industry::create(['id' => '93', 'name' => 'Warehousing']);
        Industry::create(['id' => '133', 'name' => 'Wholesale']);
        Industry::create(['id' => '142', 'name' => 'Wine and Spirits']);
        Industry::create(['id' => '119', 'name' => 'Wireless']);
        Industry::create(['id' => '103', 'name' => 'Writing and Editing']);
    }

}